### ISSUE TITLE
Cooldown with mongoose

### ISSUE THREAD

**Issue by NotSoMik** [brblacky/lavamusic#367] opened 2022-10-27 07:12 UTC
### Description of your suggestion

Well it will be cool if you make a cooldown system with a database, it will also prevent users from spam

**Comment by nfsmaniac** [comment] 2022-10-27 16:58
Sounds like a duplicate of #337 
For a good reason, any rate limits/cooldowns are applied on the very last end, which is the user interaction (text command) here.
By the "fix" you are suggesting, you would more likely create even more errors than you would actually resolve by that.

**Comment by NotAditya69** [comment] 2022-10-27 17:20
Cooldowns are meant to be caches and not parmanent so there's no use for using mongoose

**Closed by NotAditya69** 2022-10-27 17:20 UTC
Labels: Type: enhancement
