### ISSUE TITLE
Cannot start bot

### ISSUE THREAD

**Issue by aScriptingOreo** [brblacky/lavamusic#441] opened 2023-04-13 00:56 UTC
Docker Log
 ```sh
 *  Executing task: docker logs --tail 1000 -f 7541000ceaa978de26df6aa43aebae22178920a87f4ef06bd5b044d7180bbb33 


> lavamusic@3.1.0 start
> npm run start:bot


> lavamusic@3.1.0 start:bot
> npm run build && node --enable-source-maps dist/index.js


> lavamusic@3.1.0 build
> tsc --project tsconfig.json

sh: 1: tsc: not found
```

Docker Image ``ghcr.io/brblacky/lavamusic:main``

**Comment by WolverStones** [comment] 2023-04-13 01:32
You are probably missing a typescript. Check if TypeScript is installed by running the command "tsc -v". If it is not installed, you can install it by running the command "npm install -g typescript".
If TypeScript is installed, check if it is added to the system's PATH environment variable. You can do this by running the command "echo $PATH". If TypeScript is not listed, you can add it to the PATH by adding the following line to your shell profile file (e.g., ~/.bashrc or ~/.zshrc):
export PATH="$PATH:/usr/local/lib/node_modules/typescript/bin"
If the above steps do not resolve the issue, it may be a problem with your Docker container. Make sure that TypeScript is installed in the Docker container, and that the container's environment variables and PATH are properly configured. You can also try running the "tsc" command with the full path (e.g., "/usr/local/lib/node_modules/typescript/bin/tsc") to see if that resolves the issue.

**Comment by aScriptingOreo** [comment] 2023-04-13 16:15
```yml
FROM node:16
WORKDIR /opt/lavamusic/

# Copy dependencies first to improve layer caching
COPY package*.json ./
RUN apt upgrade -y && apt update -y
RUN npm install -g npm@9.6.4
RUN npm install --production
RUN apt install node-typescript -y
#RUN npx prisma generate

COPY . .

CMD [ "npm", "start" ]

```
Adding a few lines to the Dockerfile seems to have done the trick, but it can't be efficient...

**Comment by PixelHir** [comment] 2023-04-14 19:27
The problem is that typescript is defined as devDependency meanwhile the Dockerfile installs only production dependencies which causes tsc to be unavailable. Tbh the best approach is to build the typescript code in dockerfile, and the container should run the compiled code only.
This is an issue that has to be resolved by @brblacky or in a PR.

**Closed** 2023-04-24 00:23 UTC

**Comment by BetaTester41** [comment] 2023-04-27 06:11
I seem to still have this problem despite using the latest image. Could it be something with my docker, as I'm using the current docker-compose file?
